{{- if .Values.features.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-config
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMapData }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}